###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

networks:
  backend:
    driver: bridge

services:

  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    networks:
      - backend

  mysql:
    build: phpdocker/mysql
    container_name: ecommerce-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teste_db
      - MYSQL_USER=terecoteco
      - MYSQL_PASSWORD=a4qQR66CgkC9meMw
    networks:
      - backend
    ports:
      - "8083:3306"

  webserver:
    image: nginx:alpine
    container_name: ecommerce-webserver
    working_dir: /application
    depends_on:
        - php-fpm
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - backend

  php-fpm:
    build: phpdocker/php-fpm
    container_name: ecommerce-php-fpm
    working_dir: /application
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

